<!doctype html>
<html>
<head>
<title>Player</title>
<style>
*, *:after, *:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
body {
  background:#f0f0f0;
  background: url(background.jpg) no-repeat center center fixed; 
  background-size: cover;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
img {
  max-width:100%;
}

.card-grid {
  width:100%;
}
.card-grid:after {
  content: "";
  display: table;
  clear: both;
}

.card-wrap {
  float:left;
  width:100%;
  padding:5px;
}
@media (min-width: 500px) {
  .card-wrap {
    width:50%;
  }
}
@media (min-width: 720px) {
  .card-wrap {
    width:25%;
  }
}
@media (min-width: 900px) {
  .card-wrap {
    width:20%;
  }
}


.card {
  background-color:white;
  border-radius:5px;
  border:1px solid #ccc;
  border-bottom:2px solid #ccc;
}

.card:hover {
  background-color:#eee;
}
.card.active {
  background-color:#ddd;
}

.card > div {
  padding:0 1em;
}

.playlists {
  padding: 50px;
}
a {
  text-decoration:none;
  color: #333;
  line-height: 1em;
}
</style>
</head>
<body>
<?php $colors = ["#ffb3ba", "#ffdfba", "#ffffba", "#baffc9", "#bae1ff"]; $i = 0; ?>
<div class="playlists-wrap">
<div class="playlists">
<div class="card-grid">
  <div class="card-wrap" style="min-width: 33%">
    <div class="card">
      <div>
        <h3>
          <span id="now">None</span>
<?php if (isset($this->admin) && $this->admin): ?>
          <span id="next"style="float:right;cursor:pointer;">&#9193;</span>
<?php endif; ?>
        </h3>
        <audio src="/mpd" controls autoplay></audio>
      </div>
    </div>
  </div>
</div>
<?php if (isset($this->admin) && $this->admin): ?>
<?php foreach ($this->playlists as $key => $value): ?>
<div class="card-grid">
  <div class="card-wrap">
    <div class="card" style="background-color: <?= $colors[$i++ % count($colors)] ?>">
      <div>
        <h3><?= ucfirst($key) ?></h3>
      </div>
    </div>
  </div>

<?php foreach ($value as $title => $path): ?>
  <div class="card-wrap">
    <div class="card">
      <div>
        <h4><a href="#" class="play" data-playlist="<?= $path ?>">&#x25B6;&#xFE0F;&nbsp;<?= str_replace('-', ' ', $title) ?></a></h4>
      </div>
    </div>
  </div>
<?php endforeach; ?>
</div>
<?php endforeach; ?>
<?php endif; ?>
</div>
</div>
<script src="/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script>
$(function() {
    $('.play').on('click', function() {
        $.post('/play', { playlist: $(this).data('playlist')});
        $('.card').removeClass('active');
        $(this).parents('.card').addClass('active');
        return false;
    });

    $('#next').on('click', function() {
        $.post('/next');
    });

    setInterval(function current() {
        $.get('/current', function(data) {
            $('#now').text(data.current);
        });
        return current;
    }(), 2500);
});
</script>
</body>
</html>
